Update patch set 2
Patch Set 2:

the issue does appear to be due to changing the logger to "static" - because of the change, the following is generated:

NoMethodError: undefined method `logger' for #<Java::OrgOnapPolicyApexCoreEngineExecutorContext::TaskSelectionExecutionContext:0xc758a2d>
  <main> at <script>:21

might be sufficient to just add a getLogger() method to the relevant classes.  Otherwise, may have to remove "static"

Patch-set: 2
Reviewer: Gerrit User 811 <811@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>